keybase:
  api: https://keybase.io/_/api/1.0
  users:
    - name: sundeer
      email: rick11@rhsjmm.com
      root_token: true
      key_shares: 1

vault:
  url: http://server-1.rancher-vault.default.corngoodness.com:8700
  domain: toomanytubes.com
  threshold: 1
